name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_CONFIG: app.config.TestingConfig   # use your TestingConfig in CI
      DATABASE_URL: sqlite://               # keep tests on SQLite
      SECRET_KEY: test-secret
      FLASK_ENV: testing
      AUTO_MIGRATE: "0"                     # never auto-migrate during tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover tests

  deploy:
    # only deploy on pushes to main, and only if tests passed
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "accept: application/json" \
            -H "content-type: application/json" \
            "https://api.render.com/v1/services/${SERVICE_ID}/deploys"
