name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_CONFIG: app.config.TestingConfig
      SECRET_KEY: test-secret
      # optional: point tests to sqlite file
      DATABASE_URL: sqlite:///test.db
      FLASK_ENV: testing
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # if you use pytest:
          # pip install pytest

      - name: Run tests
        run: |
          python -m unittest discover tests
          # pytest -q

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -sS -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "accept: application/json" \
            -H "content-type: application/json" \
            "https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys"
